export const amenities = [
  "Air Conditioning",
  "Water Heater",
  "Washing Machine",
  "Fully Equipped Kitchen",
  "Cable/Smart TV",
  "Internet Ready",
  "Balcony",
  "Private Bathroom",
  "Furnished",
  "Built-in Closets",
  "Elevator",
  "24/7 Security / CCTV",
  "Parking",
  "Gym / Fitness Center",
  "Swimming Pool",
  "Rooftop Garden",
  "Free Wi-Fi (Common Areas)",
  "Laundry Area",
  "Garbage Disposal",
  "On-site Maintenance",
  "Playground",
  "Pet-friendly Facilities",
];
